### ISSUE TITLE
N960SC外接显示屏不识别

### ISSUE THREAD

**Issue by AoXIUy** [RiXiangXiaMei/Clevo-N960SC-N960SDS-N960SF1-Hackintosh#2]
膜具是N960SC 神舟TX9 CU5DK 核显DP外接显示屏不识别 开机之前接外接屏幕有显示，开机进度条跑一半就黑屏带点闪屏 外接内屏都没显示

**Comment by RiXiangXiaMei** [comment]
收到，我尝试修复一下，但是我没有外接显示器，可能修复不成功

**Comment by AoXIUy** [comment]
![mmexport1652766815089](https://user-images.githubusercontent.com/78833411/168738860-6b3589c1-cba5-4c5b-8b60-8b78b6eaae97.jpg)
大佬我自己改了一下这样可以外接显示内屏不显不过外接会闪屏

**Comment by AoXIUy** [comment]
![Uploading IMG_20220517_140450.jpg…]()

**Comment by AoXIUy** [comment]
![Uploading mmexport1652767661026.jpg…]()

**Comment by AoXIUy** [comment]
![mmexport1652767661026](https://user-images.githubusercontent.com/78833411/168741870-5af88641-96a1-4680-924d-a1e9e8f55c59.jpg)这是显示后hackintool里面显示的接口

**Comment by AoXIUy** [comment]
我自己修复好了
![IMG_20220520_133459](https://user-images.githubusercontent.com/78833411/169457871-746c3ebe-7417-48b0-a12c-4b6c35a3f656.jpg)

**Comment by JackyChung1** [comment]
> 我自己修复好了 ![IMG_20220520_133459](https://user-images.githubusercontent.com/78833411/169457871-746c3ebe-7417-48b0-a12c-4b6c35a3f656.jpg)

你好，请问一下你是怎么修复好的呢，谢谢！

**Comment by AoXIUy** [comment]
输出接口问题需要改核显配置

**Comment by AoXIUy** [comment]
你需要我的配置可以联系我 q 2739632934同模具应该是一样的

**Comment by AoXIUy** [comment]
我发了修复的分支
